export const TODOS_HAS_ERRORED = 'TODOS_HAS_ERRORED';
export const TODOS_IS_LOADING = 'TODOS_IS_LOADING';
export const TODOS_FETCH_DATA_SUCCESS = 'TODOS_FETCH_DATA_SUCCESS';
export const TODOS_ITEM_TOGGLED = 'TODOS_ITEM_TOGGLED';