enum TodosConstants {
    TODOS_HAS_ERRORED = 'TODOS_HAS_ERRORED',
    TODOS_IS_LOADING = 'TODOS_IS_LOADING',
    TODOS_FETCH_DATA_SUCCESS = 'TODOS_FETCH_DATA_SUCCESS',
    TODOS_ITEM_TOGGLED = 'TODOS_ITEM_TOGGLED'
}

export default TodosConstants;